#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

script_dir() {
  local FILE_SOURCE="${BASH_SOURCE[0]}"

  if [[ -L ${FILE_SOURCE} ]]; then
    dirname "$(readlink "${FILE_SOURCE}")"
  else
    (
      cd "$(dirname "${FILE_SOURCE}")" && pwd
    )
  fi
}

main() {
  local SCRIPT_DIR
  SCRIPT_DIR="$(script_dir)"

  source "${SCRIPT_DIR}/scripts/meta" && meta_init "var"
  var_color

  local DESTINATION_FOLDER="${SCRIPT_DIR}/ffmpeg"

  for arch in amd64 arm64 armhf; do
    local ARCHIVE_NAME="ffmpeg-release-${arch}-static.tar.xz"

    local DESTINATION_ARCH="${arch}"
    if [[ ${DESTINATION_ARCH} == "armhf" ]]; then
      DESTINATION_ARCH="arm"
    fi

    local TARGET_NAME="${DESTINATION_FOLDER}/linux/${DESTINATION_ARCH}"

    if [[ -e "${TARGET_NAME}/ffmpeg" ]]; then
      var_info "File already present for linux/${arch}, skipping download."
      continue
    fi

    var_info "Downloading static ffmpeg for linux/${arch}"

    curl --disable --silent --show-error --location --max-time 600 --remote-name "https://johnvansickle.com/ffmpeg/releases/${ARCHIVE_NAME}"
    mkdir -p "${TARGET_NAME}"
    tar -xf "${ARCHIVE_NAME}" -C "${TARGET_NAME}" --strip 1
    rm -rf "${ARCHIVE_NAME}"
  done

  # Update cache value in CI
  # CACHE_VALUE="$(date "+%s")" yq eval --inplace '.jobs.package.steps[] |= select(.name == "Cache LFS") |= .with.key |= "lfs-" + env(CACHE_VALUE)' "${SCRIPT_DIR}/.github/workflows/build.yaml"
}

main "${@}"
