apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vith
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.79"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: vith
    image:
      name: vibioh/vith
      tag: "202202012230" # {"$imagepolicy": "default:flux-vith-api:tag"}
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: vith
    volumeMounts:
      - name: data
        mountPath: /data
    config:
      VITH_LOGGER_JSON: "true"
      VITH_STORAGE_DIRECTORY: "/data"
    secrets:
      VITH_AMQP_URI: AgABgjryaveps/8s8eZP83UjLt9nxzqNT74kzAZaYBTWErvyY+aV+XN7W2VJdWZgS8B3lEvBhpeEMoVQQweTXwSKSVHt8B1Pxl8iI3q+8jnEqEJ+g3F6azlj4A4wu5kIBge+4/tSRq5pLFdSZB6nx9YSPfpSFoObXx8AyXwPWN3GVlBTu+hiTDzEo/EJIVKtRxQlvV1W0VM///D7eZGf+snhChQvz8ZPqwaDTKyGiJPjfVFFZ/IP06DpRakOgMcAftazy8qWRSvQPQpHtkU1QPjY57+/uGrBqmRiLJmcaqJSN2o34VDGhND1VqV8al4vG4MU+crvRo1HH6RKOwikGzAxlLmBmL/yP/tGE9JAkrWtDgi9AwuiDvvcVtCU1/pvBAOTyoImTXd9J9yrZBH47jrIlMfRKTi0z/PRJpjkHrzAcdUHauPLDrXiz4+iaqc3GI6fRx27+gxOHGKjppFZqU9BmfNip4D1IBKP/cdOa9mysRLyeQM5e23Z45Z7Cfg3hUvt3hAco/QMAc2QuvJRLbZT2No4NJcW4j0OmMdS139TCXEQZpjHE0NkHmA27W1U8FyTd6sXPF8o8OZkyVWTzym1OViK4rxvG/vAanPAocdwUAuZ3cAbYrKsAfvs5t99kmLb2ysztzXGSwytL/t7kH6S0cDPOjODNAOMyEKMHfsBhueYX/3bpg64cyutnxCdx73qOo2dIQBeZlcW2rp4WGmq+dBFuwFHf2ZZS4oe7GlB1bAVdUe+oCH4HdeARoam/hwNMcsxJnLr201GbA==
      VITH_IMAGINARY_URL: AgCdp3Vep19qT2G/6M7Zn5ffYLNKez9UdV0zHQHwDoNHlLTXS9bDfaSDzlvMfl0qVJGo1VfhlOvLhYP4SjRDNG4gSOS2fgf0KoXbvCvwHr9xxG0kFR9rSF2fzquxgjJhHlGG4APy7T/ScU4/yJAtXYnh2UKknADLHS01ZUE8APB+AhNanUc5Ty4ygn3B8GmHXnjuadPt6vjxbm00gZ/mp90fpGIyToF/uFnh8XgXUrVKf4kieGSRS29HyWImzbQobmS+K0b1dzyYYkdOePPMIHfBWdkFiwtP7qJl1Uw5OQaPrxhyjCX8/nYtjxNDOyQVHAvnClsPOCThd75Kf0wrIV1gdR+Q6E7C0Kh0jptjMCLpgch2cmQqPmTMoZ6Yv9gwcsX57Oc7XhR0wPCcCqfdHmJi0EbVghqZMabjsMkFA8KBOwt9n1NtJY5Hvf4ux0Zyywty7bI1FTjKR+I6MKopzQvMd5AxYEg9Rp/oza2JNLcPMrkL5543XPtu/JosQ9C0EKKNg6IGIxPP7YOOeLzZfKjUdWs5k1/x6r4gNyDHCmUoGpXFfCgJAmVNg1bwGZt61CC/9m+sxQfEk0rKTcSoYbYZDgI9N/+iCy67ldwdTXy81+9fW1Ag7RQzbP6pjXlBolSK684spQ65C6V8P+cv/r8A3lpAk3j+3WPV+LszPnRQ0eaMXNoOhciqXvwR7E71K9L/JBjJP0Duo3xk6o42Q6skUSUyyARWH4XuvtNCNlwAjOGWWdexr363cjDfve6mUKSX0CPkjLzMfJ3glUw4hNQ=
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/storage
        operator: Exists
    resources:
      limits:
        memory: "1Gi"
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
    autoscaling:
      enabled: false
