apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vith
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.75"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: vith
    image:
      name: vibioh/vith
      tag: "202110090719" # {"$imagepolicy": "default:flux-vith-api:tag"}
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: vith
    volumeMounts:
      - name: data
        mountPath: /data
    config:
      VITH_LOGGER_JSON: "true"
      VITH_WORK_DIR: "/data"
    resources:
      limits:
        memory: "1Gi"
    securityContext:
      runAsGroup: 995
      runAsUser: 999
    autoscaling:
      enabled: false
