apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vith
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.81"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: vith
    image:
      name: vibioh/vith
      tag: "202206171930" # {"$imagepolicy": "default:flux-vith-api:tag"}
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: vith
    volumeMounts:
      - name: data
        mountPath: /data
    config:
      OTEL_SERVICE_NAME: vith
      VITH_LOGGER_JSON: "true"
      VITH_STORAGE_FILE_SYSTEM_DIRECTORY: "/data"
      VITH_TRACER_URL: http://jaeger.monitoring:14268/api/traces
    secrets:
      VITH_AMQP_URI: AgCVS4yp43cwsm8qccTe+uWtEfVlj/p+FTMbSSJrCrHhVAe0pca5hbvCbpdWncLZnnOiK4nTeW7jKl7Hkbh92YZCImTIVyN0NhERI5ZPzm9g59pLTORYw1OgHQuc0lcazv5TxRQz7vMLT5deUDwAH6jlZZT24+lEFZgLtFcBgJNr1uwrKRlFQ5y035rfRJBy5O/NaiwANwtB6TsupQX+GLRsjSNPxsnhoQzubZ2O/kr1UgaANunnushNQYpip/vQMEBFPZd2ZhWUhRuEWt/RfMkBFqanqi8DT6TMm1TTTap0xxhr6W6kR2iHq9LBj15ZkACRttV9dyzLSnuVhcFY7LSCraaomTwXdFkHhpkLkJGqUjWjtytrWdvUP6HKZy305s9BVAOfnjHjH7ZCcmeKOHEMYcm13KN0F61hLk4EenaeDnNzg6iJGvD3wWint//xFddRksX8bz3lXhjMen82x1yVloahqCSUbwBIv2IOksYKBOp43qy3Qa1gm8SxyidwaZDdVO/D7vruD1BbMRPEic2mQ+AWX0U8RCp9c5cJdSQ+eX/EsPRiamEmBO5+yo/oZk7rtn3EEC7HGzzM4H57dYiwXtxsM8ouGPClBn8L2k5RPOK1a20YoTu/roN/ZyWJM09aWFgrq3LmpT79LSUbBhmAzSUX6+wLLI7mid9mQEm3+9IRFcPjTD4aFsdp53Lwu4m6TuwQR8c4PHm7OwpLReeMJA/oqXs543WH0kJxavFlUTyjKNPxNigAsrgDCAgCFBlBJ+A=
      VITH_IMAGINARY_URL: AgCMp9i6naI7iL59DEuwZYETD+0KJzTTLaQsLBlGKLApa9I7o0V2LfVWZeHtRyINr8EpbHkmSMecw6IqvEwtCmw2JF0nG/pxJgMwbSmpdRtjOcSHGkfyea/PLsmrPqBMYarkqQJH2X83VhoU0HmvtA64xxwKFuo+wWKqpPfNaM9LqECrYdeEHtyhQmcB3qEFbYsPRif9QROyBWphrwv9Tz1Tt9Bg1iTVe8y+SgCo8YQNC3VEP5A4sFCpp/JxoMSfge3Ly3h1ZuU0O3y7gKIlUo2ks8eF9dU5bF/vS/H9FihRPrbYhYxSOqEXzMepKmmt6t8inPqHgzKRlck1CnZI7/NXthIVVgJz6O3iy8cBqC72jDXF9WkfVFC0XGRPt9UW5T/PRUs2+4lLii23HZvuR/YkIq0+A31GUGa1Rr+4qZdYgCbQ+dupBo/wglAlvYs6QYV3zfob9XGK8+qpibGNkhO4KhlujYiPYaQuwivXH0NfbXTimtA+02X6HO9orJxy/TtiA+Bb1GUgg22mGbVKNHfkj3AfCTvOI3QBHYOtGQaXYhwE3Y2vGVZ8mHZkjIi413YNhMxPcl271XyjozBU9oARuDE/QtMhTj098L46f6ukJr7qyCUgry1srh/aFfkkflVFtULDnRmPn+hUG/cOv+jUKkVoAaedgyetpPUhJNvolvKffo5Rox5kHsuFNue3QVLXiJOybafhDLbkI+qbgA/bAdsGgWd3CvbtNAc4ecLSlyT6BKJZr6h4VpuRVNHqLFDp2/oNjKIZipCYFcpQz3Q=
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/storage
        operator: Exists
    resources:
      limits:
        memory: "1Gi"
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
    autoscaling:
      enabled: false
    pprof:
      enabled: true
