apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vith
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.81"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: vith
    image:
      name: vibioh/vith
      tag: "202206251603" # {"$imagepolicy": "default:flux-vith-api:tag"}
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: vith
    volumeMounts:
      - name: data
        mountPath: /data
    config:
      OTEL_SERVICE_NAME: vith
      VITH_LOGGER_JSON: "true"
      VITH_STORAGE_FILE_SYSTEM_DIRECTORY: "/data"
      VITH_TRACER_URL: http://jaeger.monitoring:14268/api/traces
    secrets:
      VITH_AMQP_URI: AgAlPWAdD96jx5aiKfU8YIEpPVHzCQm/1FWii6rojaKgcSh4Y1qnWBH5hCBwlMeHg/PE72IWho3/wAgktQElEKK7qrBaRkAjZsVxbpfWrZnfuuL5QBBnQMX4RIF0/Xc5W9ht+qJjVSxJmVIzYBsdcZ5gkmqJPinm4yoiCoppjnXJfvhKHh9kCbNySC+8bsdqPF2rZRVEa3pHqiVw5JRu/1TXempqZ6kPKMdXahGO8W6v+1uTxAKeG7cfH6cjlv6ZUZuzPDwGM05vjPPCPTht5rFhZA/dPwvfXtgsY9VHuxIqQACzb0KQNhru2E/HOjH3FnwQESkyBXh/IcsR3n5KfUiXTbkFniKFsvDg8vq9wNHyDnmYYHOd5nnvjvm+AMMjaLg3ovc2EUyYOYZ3bwWv3xknSp9AWFP7ic3lhIMz6gUM5aXZZ6rI8LrHqsCQ86JwodD0g1nzfsCxZ1rHGzuvKNrRyLgbF+W6l9CRUri6gkus9BYfhgjmHCqrKZPNwru8adphvIAzoVFxFBPiCH/u+chJOklMQ7hgGojA4z70X6a5SaIWYIZuVnUCmYBLg5t2Ps+wlbY/CZhexoBSD5Joa9ohPYmFEktnNyNySFLuXV+TdUbY3yto4ib5/01BRNqYspaEnLg6AqY+cKh+PgBVuYzr+d3UMvJcuG0hezsMp0CZgCSUga6/oeLsh74f2vMOGx6rfaDbD70uCHlBBvMqZVM0Qdv7pxK9qhaIcA31c3oIeFlUkMlG0vggdQqTjp3Jz+0LNyU=
      VITH_IMAGINARY_URL: AgAAHaYxy+aMRtnjDt6soeazUQrfEiNzoYcSBJqzBVZn0LkISWw4/zNYVEcBtyl5NmSoqIBT5sp7xp6U20M5cCALnI/lxCfuASRyzXZke44TfZcvIAi/NobGJwXN04Zk2+OJax82A5PJD2ZwDJtgueoEPO/bFHJN9K01cVKn7JA1pedvRxWpj8kO5koGrZa+wLtjwYSHaBThop00HF9j1Ns6x4/jMZTEVxpPVtruD5yEWpl81fgK7jJcytV4fQxisw+X102lIEsw1XFZOgxm0bPc2tHkX/H0qBwQFqxfZiUH7+7p3owdKvIvhR3ev2UnI/7BPL3B9seKWkUjdER60JNzCdfIyTS6in9hpwE8oR/1qtLwk/CDK9UqpToV8GwIY+u80xwq0ZWTgRKgeD/clRGMy4NLGAD74MS781ai0aDFhn8P0zcRhn6f/5m8PFeIAmUv9JcBGwu8xZprx30Q2Pk223eJQ86IL7MpiE5gt/IefIhG7nrD4cUjemYkTPzLAAvMzSVSvdNlfONsusmAxtIgCdMgYD9boelZlOJghzN7DH7eo58eXBgRHja71nX/fO/9YgI0jgHdhJWoUZgCBCnB/8n93YM3nDSF7oPFcHqF4xWMywig9Fdq+ul1gsa/VxKkxDuBVRJJDYiKQzc96QVg8jhdstHnnKA3cvPUydPQT/8wcr2efdwELJ0WoQKiv7uLP9AJd2D1waBX826niZ1YjEvCd8/DroC2PmYKhg52kDYtLnyWoUXPqAf66WN5flWXDtxN/VTy4Hx9xvzYJX8=
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/storage
        operator: Exists
    resources:
      limits:
        memory: "1Gi"
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
    autoscaling:
      enabled: false
    pprof:
      enabled: true
