apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vith
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.92"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: vith
    image:
      name: vibioh/vith
      tag: "202312152354" # {"$imagepolicy": "default:flux-vith-api:tag"}
    strategy:
      type: Recreate
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: vith
    volumeMounts:
      - name: data
        mountPath: /data
    config:
      GOMAXPROCS: "1"
      OTEL_RESOURCE_ATTRIBUTES: env=production,git.repository_url=github.com/ViBiOh/vith
      OTEL_SERVICE_NAME: vith
      VITH_LOGGER_JSON: "true"
      VITH_STORAGE_FILE_SYSTEM_DIRECTORY: "/data"
      VITH_TELEMETRY_URL: datadog.observability:4317
    secrets:
      VITH_AMQP_URI: AgB6KA3PIGrgkh1VSzZTAILwMrarWvRjsktCGCrymwA7w6DqvDTzLwA2UlfxqSmCSkxm1D105HlaXWhp1MszYkvVeGVANvbYozViCHCC5LudSI6zPbmnuqsHmGWOXVa8g6dLSNyRNnj6u8MzKwClSrreEsKdo3q9YDvpIe3PtwMhjqAq3fOOtjoXyxnyyj4KlksfMYfCcp+VhT0pB04poSvyNwz0TYxJqkOXG/kUOhAOuI6HG2286QcyzJa9QRps+iiJXFNJ2pw8QeGB5v+T6ijmFeVrwQKXYhvt42WsutXovjKwxDpzBTOfSkE4M67bhVgC1JMP6Fqz3Tc6P9O0WZRGDNV1U2pXKHYBuYplkIXmAr2KabIv1l2pDiCINrzQGdkUc9r7aSFL6nIKFAmLNb+47Hyv80ViHHG5kOfM2xwspcOdzj1zJ49RfGne8toHZYfuFvAC1u5RpSTI9fO4OeIoMh4rXl8yE4eNiqT3o46cN7Fsj3UhPfr3bHx6UG+9xFrC/cvRPf8UNi28XT24Rvi3zD5bK66BCYX8jBFidicbMQgL/D/HWb5iDYzo8Y2n4YE1qPib5dvRpLxWQEZOQWHirk4jKtxg3L/WZmETHQd+P97T1Hp7Chch+RBAx2vvImb07/RvLfDr7sR+PD9T6HMPvifiawsFW15hMfwnQYN5nv9iYiCJbJaRvO6XI9r8Ts8ynkJMDgbzRfArnHPGEKLtmy5RR9wd28qCn7KTwXNby92gr1NhQsa+XTuIAciYBFCj
      VITH_IMAGINARY_URL: AgBQU5RbyOwVygoPDdszwSqMibgrB9mvfu82rBfs/tPZ2QAoPxzWKgY/OQ1Z6W2bK/SYHpM4Lx1yBNi+8z8zPxvvlc4VZbLcJE9VPIDHzHGLUKdq3zO7FW4MpxNQFZ2tQRJKQ1n8z9mx9iVhA56SLVR8efwUPDgeV8oOS1bMqGhyyuDlZYR2Z9SWYfiuBQ3zTNNz6oxlgwYU7BkxEbWuaZZTxvjvxiBQtD64nqhlMESXt9A+rwOsNpr8ssKjKGij2ILXoZeiPUHLY33yUwKXSQTm7DU+W5viqTQgOMa/SHgP3BE+Wcwu6v/3Q58embZYp3Bn3xcd1VpD01GPGvHChJmqxOQqnolgIDA+u7DSji0Uebx2NiVMczlKJUmrIHg/sLygHuEobsjtmDjGHrT3y8KJi2sOnh8Ei7SMZDQoS04AUDHaYx7ZrwyrKm36kFyAtOYAF17ddeHfqSyqBojdiuQ8pRA9rubUwX8xgVgVzmw7PwlDtAuUK2F/vPXFL+/hnOkB1hrPRzAKL/sa9H5W1hS25YSEIflNCpQgERKeQeXuFMORFxPeZBBUcq2demmDNzIdJTjAnhIweMZqlUgnz0NI2tiQlr5+kDuMYahO8BE3ienNeGhLPGodK1tXNY/3K3GUqvo5uTlrZtkvO0Yqj3XKJVY4e4HmO5g0SEr6ua1jdI5FcggtxtnGRG20S6+Rd6L5tDBT9vm+s+hRgP172NowziBuzdSWH6oTkg3O6A13OZxjbYxN57SafcIyS9bTwuoSRhgenyGLutn6/SS4qzY=
    resources:
      limits:
        memory: "1Gi"
      requests:
        memory: "256Mi"
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
    autoscaling:
      enabled: false
    pprof:
      enabled: true
