apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vith
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.32"
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: flux-system
      interval: 120m
  values:
    nameOverride: vith
    image:
      repository: vibioh/vith:latest # {"$imagepolicy": "default:vith"}
    config:
      VITH_LOGGER_JSON: "true"
    resources:
      limits:
        cpu: 100m
        memory: 1G
      requests:
        cpu: 100m
        memory: 100Mi
    autoscaling:
      enabled: false
